n = input("Dime el nombre del producto:")
p = float(input("Dime el precio:"))
u = float(input("Dime el Nº de unidades:"))
print(n, "cuesta", round(p,2), "€ la unidad y hay", u, "unidades. Precio final:", round(u * p,2), "€")
input()
