nombre = input("Dime el nombre del producto:")
precio = float(input("Dime el precio:"))
unidades = float(input("Dime el Nº de unidades:"))
print(nombre, "cuesta", round(precio,2), "€ la unidad y hay", unidades, "unidades. Precio final:", round(unidades * precio,2), "€")
input()
